---
yum_update: True
yum_cleanup: True

absent_packages:
  - ruby
  - rubygems
present_packages:
  - ca-certificates
  - bash
  - sudo
  - curl
  - autoconf
  - automake
  - libtool
  - bison
  - make
  - patch
  - gcc-c++
  - readline
  - readline-devel
  - zlib
  - zlib-devel
  - libyaml-devel
  - libffi-devel
  - openssl-devel
  - git
