---
- name: clone
  git: repo={{ project_repo }} dest={{ project_prefix }} version=HEAD
  tags: git

- name: bundle install
  command: "bundle install --deployment --without=development,test --binstubs --clean --retry 2 --path=vendor/bundle chdir={{ project_prefix }}"
  environment:
    RACK_ENV: production
  register: _bundler
  changed_when: _bundler.stdout.find('It was installed into')

- name: bundle check
  command: "bundle check --no-color chdir={{ project_prefix }}"
  register: _bundler_check
  tags: bundler
  failed_when: _bundler_check.rc == 127
