---
- name: remove packages
  yum: name={{ item }} state=absent
  with_items: "{{ absent_mandatory }}"
  sudo: True
  register: _yum_remove

- name: validate package removal list
  fail:
    msg: "invalid state: {{ item }}"
  when: "not item.find('is not installed')"
  with_items: _yum_remove.results

- name: upgrade
  yum: name=* state=latest
  sudo: True
  register: _yum_upgrade
  tags: upgrade

- name: install missing
  yum: name={{ item }} state=present
  with_items: "{{ present_mandatory }}"
  sudo: True
  register: _yum_install

- name: validate installad packages
  fail:
    msg: "invalid state: {{ item }}"
  when: "not item.find('is already installed')"
  with_items: _yum_install.results

- name: autoremove
  command: yum -q -y autoremove
  sudo: True
  register: _yum_autoremove
  changed_when: "_yum_autoremove.stdout != ''"
  when: "yum_cleanup == True"

- name: clean all
  command: yum -q -y clean all
  sudo: True
  register: _yum_clean
  changed_when: "_yum_clean.stdout != ''"
  when: "yum_cleanup == True"
