---
- name: setting yum repo priority
  ini_file: dest=/etc/yum/pluginconf.d/priorities.conf
            section=main
            option=enabled
            value=0

- name: remove packages
  yum: name={{ item }} state=absent
  with_items: "{{ absent_packages }}"
  register: _yum_remove

- name: validate package removal list
  fail:
    msg: "invalid state: {{ item }}"
  when: "not item.find('is not installed')"
  with_items: _yum_remove.results

- name: update all
  yum: name=* state=latest
  register: _yum_upgrade

- name: install missing
  yum: name={{ item }} state=present
  with_items: "{{ present_packages }}"
  register: _yum_install

- name: validate installad packages
  fail:
    msg: "invalid state: {{ item }}"
  when: "not item.find('is already installed')"
  with_items: _yum_install.results

- name: autoremove
  shell: yum -q -y autoremove
  sudo: true
  register: _yum_autoremove
  changed_when: "_yum_autoremove.stdout != ''"
  when: "yum_cleanup == True"

- name: clean all
  shell: yum -q -y clean all
  sudo: true
  register: _yum_clean
  changed_when: "_yum_clean.stdout != ''"
  when: "yum_cleanup == True"
