---
- name: varnish | add repository file
  copy: src=varnish.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644
  sudo: true

#- name: varnish | enable repository
#  ini_file: dest=/etc/yum.repos.d/varnish.repo
#            section=varnish-4.0
#            option=enabled
#            value=1
#  sudo: true

- name: varnish | erase
  yum: name=varnish-* state=absent
  sudo: True
  register: _yum_erase
  tags: remove

- name: varnish | install missing
  yum: name=varnish state=latest
  sudo: True
  register: _yum_install

- name: varnish | check
  shell: varnishd -V
  environment:
    PATH: /usr/sbin
  register: _varnish_check
  failed_when: not _varnish_check.stderr.find('varnish-4')

- name: varnish | configuration template
  template:
    src=$repository_basedir/varnish/templates/varnish.default.j2
    dest=/etc/default/varnish
    owner=root group=root mode=0644
  notify:
    - varnish-restart
  when: False

- name: varnish | ensure daemon gets started
  service: name=varnish state=started
  when: False

