---
- name: add repository file
  copy: src=varnish.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644
  sudo: true

- name: erase package
  yum: name=varnish-* state=absent
  sudo: true
  register: _yum_erase
  tags: remove
  when: False

- name: install package
  yum: name=varnish state=latest
  sudo: true
  register: _yum_install

- name: setup configuration
  template:
    src=etc_sysconfig_varnish.j2
    dest=/etc/sysconfig/varnish
    owner=root group=root mode=0640
  sudo: true

- name: check
  shell: varnishd -V
  environment:
    PATH: /usr/sbin
  register: _varnish_check
  failed_when: _varnish_check.stderr.find('varnish-4') == -1

- name: start service
  service: name=varnish state=started
  sudo: true
  when: _varnish_check|success
