- debug: msg="instance type {{ ansible_ec2_instance_type }}"

# t1.micro
- sysctl: name=kernel.shmall value=268435456 sysctl_file=/etc/sysctl.conf reload=no
  when: ansible_ec2_instance_type == "t1.micro"
- sysctl: name=kernel.shmmax value=4294967295 sysctl_file=/etc/sysctl.conf reload=no
  when: ansible_ec2_instance_type == "t1.micro"
- sysctl: name=kernel.shmmni value=4096 sysctl_file=/etc/sysctl.conf reload=no
  when: ansible_ec2_instance_type == "t1.micro"
- sysctl: name=kernel.msgmnb value=65536 sysctl_file=/etc/sysctl.conf reload=no
  when: ansible_ec2_instance_type == "t1.micro"
- sysctl: name=kernel.msgmax value=65536 sysctl_file=/etc/sysctl.conf reload=no
  when: ansible_ec2_instance_type == "t1.micro"
- sysctl: name=kernel.msgmni value=1196 sysctl_file=/etc/sysctl.conf reload=no

# t2.micro
- sysctl: name=kernel.shmall value=4294967296 sysctl_file=/etc/sysctl.conf reload=no
  when: ansible_ec2_instance_type == "t2.micro"
- sysctl: name=kernel.shmmax value=68719476736 sysctl_file=/etc/sysctl.conf reload=no
  when: ansible_ec2_instance_type == "t2.micro"
- sysctl: name=kernel.shmmni value=4096 sysctl_file=/etc/sysctl.conf reload=no
  when: ansible_ec2_instance_type == "t2.micro"
- sysctl: name=kernel.msgmnb value=65536 sysctl_file=/etc/sysctl.conf reload=no
  when: ansible_ec2_instance_type == "t2.micro"
- sysctl: name=kernel.msgmax value=65536 sysctl_file=/etc/sysctl.conf reload=no
  when: ansible_ec2_instance_type == "t2.micro"
- sysctl: name=kernel.msgmni value=1983 sysctl_file=/etc/sysctl.conf reload=no
  when: ansible_ec2_instance_type == "t2.micro"

- sysctl: name=kernel.printk value="4 4 1 7" sysctl_file=/etc/sysctl.conf reload=no

- sysctl: name=vm.swappiness value=30 sysctl_file=/etc/sysctl.conf reload=no

- sysctl: name=net.core.somaxconn value=256 sysctl_file=/etc/sysctl.conf reload=no

- sysctl: name=net.core.rmem_default value=65536 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.core.rmem_max value=1703936 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.core.wmem_default value=65536 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.core.wmem_max value=1703936 sysctl_file=/etc/sysctl.conf reload=no

- sysctl: name=net.ipv4.tcp_mem value="43464 86928 173856" sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_rmem value="8192 218450 6291456" sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_wmem value="4096 163840 4194304" sysctl_file=/etc/sysctl.conf reload=no

- sysctl: name=net.ipv4.ip_forward value=0 sysctl_file=/etc/sysctl.conf reload=no

- sysctl: name=net.ipv4.icmp_echo_ignore_broadcasts value=1 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.icmp_ignore_bogus_error_responses value=1 sysctl_file=/etc/sysctl.conf reload=no

- sysctl: name=net.ipv4.conf.all.accept_redirects value=0 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.conf.all.arp_announce value=2 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.conf.all.arp_ignore value=1 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.conf.all.log_martians value=0 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.conf.all.rp_filter value=1 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.conf.all.send_redirects value=0 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv6.conf.all.accept_source_route value=0 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv6.conf.all.log_martians value=0 sysctl_file=/etc/sysctl.conf reload=no

- sysctl: name=net.ipv4.tcp_dsack value=0 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_ecn value=1 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_fack value=1 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_fin_timeout value=15 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_keepalive_intvl value=150 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_keepalive_probes value=3 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_keepalive_time value=300 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_max_orphans value=128 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_max_syn_backlog value=128 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_max_tw_buckets value=256 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_rfc1337 value=1 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_sack value=1 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_slow_start_after_idle value=0 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_syn_retries value=2 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_synack_retries value=2 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_syncookies value=1 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_timestamps value=0 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_tw_recycle value=0 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_tw_reuse value=1 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv4.tcp_window_scaling value=1 sysctl_file=/etc/sysctl.conf reload=no

- sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv6.conf.all.forwarding value=0 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv6.conf.eth0.disable_ipv6 value=1 sysctl_file=/etc/sysctl.conf reload=no
- sysctl: name=net.ipv6.conf.lo.disable_ipv6 value=1 sysctl_file=/etc/sysctl.conf reload=no

# last one reloads!
- name: reloading sysctl
  sysctl: name=kernel.sysrq value=0 sysctl_file=/etc/sysctl.conf reload=yes
