---
- name: remove users
  user: name={{ item }} state=absent
  with_items:
    - games
    - gnats
    - gopher
    - irc
    - list
    - news
    - proxy
    - uucp

- name: disable logins
  user: name={{ item }} shell=/sbin/nologin
  with_items:
    - daemon
    - bin
    - lp
    - mail
    - nobody

- name: remove groups
  group: name={{ item }} state=absent
  with_items:
    - games
    - gnats
    - gopher
    - irc
    - src
    - list
    - news
    - proxy
    - uucp

- name: root directory permissions
  file: dest=/root state=directory mode=700

- name: tmpfs options
  mount: name=/dev/shm src=tmpfs fstype=tmpfs opts=rw,noatime,nosuid,nodev,noexec state=present

- name: check bash (http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-7169)
  shell: bash -c 'env x=\'() { :;}; echo vulnerable\' bash -c "echo this is a test"'
  register: _check_bash
  failed_when: _check_bash.stdout.find('vulnerable')
  tags: cve
