---
- name: git clone "{{ ry_repo }}"'
  git: repo={{ ry_repo }} dest={{ tmp_prefix }}/ry version=HEAD
  register: _ry_clone
  tags: git

- name: install to "{{ local_prefix }}"
  shell: cd {{ tmp_prefix }}/ry && PREFIX={{ local_prefix }} make install
  register: _ry_install
  when: _ry_clone|changed

# priviliged bluepill requires ruby available for root
- name: adjust path for root
  lineinfile: "dest=/root/.bashrc line='export PATH={{ local_prefix }}/bin:${PATH}'"
  sudo: true

- name: adjust PATH
  lineinfile: "dest=~/.bashrc line='export PATH={{ local_prefix }}/bin:${PATH}'"

- name: adjust LAN to UTF-8
  lineinfile: "dest=~/.bashrc line='export LANG=en_US.UTF-8'"

- name: enable ry for root
  lineinfile: "dest=/root/.bashrc line='eval $(ry setup)'"
  sudo: true

- name: enable login script for current user
  lineinfile: "dest=~/.bashrc line='eval $(ry setup)'"

- name: check version as current user
  shell: ry -V
  register: _ry_check
  changed_when: False
  failed_when: "_ry_check.stdout == ''"

- name: show ansible_env
  debug: var=ansible_env

- set_fact: _rubyry_success="true"
