---
- name: ry | cloning git repositoy "{{ ry_repo }}"'
  git: repo="{{ ry_repo }}" dest="{{ tmp_prefix }}/ry" version=HEAD
  register: _ry_clone
  tags: git

- name: ry | install to {{ local_prefix }}
  shell: cd {{ tmp_prefix }}/ry && PREFIX={{ local_prefix }} make install
  register: _ry_install
  #failed_when: "_ry_install.rc != 0"
  when: _ry_clone|changed

- debug: msg="{{ _ry_install.stderr }}"
  when: _ry_install|failed

- name: ry | adjust PATH variable
  lineinfile: "dest=~/.bashrc line='export PATH={{ local_prefix }}/bin:${PATH}'"
  #when: _ry_install|changed

- name: ry | enable login script
  lineinfile: "dest=~/.bashrc line='eval $(ry setup)'"
  #when: _ry_install|changed

- name: ry | check version
  shell: ry -V
  register: _ry_check
  changed_when: False
  failed_when: "_ry_check.stdout == ''"

